name: numbers ci
on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim
    steps:
      - run: |
          pip install flake8
          flake8

  test:
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: python:3.8-slim
    steps:
      - run: |
          pip install -e ./[dev]
          pytest

