name: numbers ci
on: push

jobs:
  # runs-on: ubuntu-latest
  container:
    image: python:3.8-slim

  lint:
    steps:
      - run: |
          pip install flake8
          flake8

  test:
    steps:
      - run: |
          pip install -e ./[dev]
          pytest

